services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: railguard-api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=https://dagshub.com/Abhishek-B16/railway-defect-detection-mlops.mlflow
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: railguard-ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: railguard-prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: railguard-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
