services:
  - type: web
    name: railguard-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile.api
    healthCheckPath: /health
    envVars:
      - key: MLFLOW_TRACKING_URI
        value: sqlite:///mlflow.db

  - type: web
    name: railguard-ui
    env: docker
    plan: free
    dockerfilePath: Dockerfile.ui
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: railguard-api
          envVarKey: RENDER_EXTERNAL_URL