services:
  - type: web
    name: railguard-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile.api
    healthCheckPath: /health
    envVars:
      - key: MLFLOW_TRACKING_URI
        value: https://dagshub.com/Abhishek-B16/railway-defect-detection-mlops.mlflow

  - type: web
    name: railguard-ui
    env: docker
    plan: free
    dockerfilePath: Dockerfile.ui
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: railguard-api
          envVarKey: RENDER_EXTERNAL_URL